column_ord: list = [
    'id',
    'item_id',
    'plus_sizes',
    'label_all_together',
    'featured',
    'Labels',
    'label_1',
    'label_2',
    'label_3',
    'label_4',
    'label_5',
    'label_6',
    'label_7',
    'label_8',
    'label_9',
    'label_10',
    'label_11',
    'label_12',
    'label_13',
    'label_14',
    'label_15',
    'label_16',
    'label_17',
    'label_18',
    'label_19',
    'verified',
    'Material',
    'search_price',
    'rrp_price',
    'delivery_cost',
    'merchant_name',
    'category_name',
    'category_normalized',
    'saison',
    'saison_conf_score_index',
    'Fashion:suitable_for',
    'Title',
    'description',
    'brand',
    'payment_methods',
    'custom_8',
    'custom_6',
    'base_price_text',
    'saving',
    'currency',
    'ean',
    'valid_to',
    'custom_3',
    'language',
    'base_price_amount',
    'model_number',
    'image_large_url',
    'merchant_product_id',
    'custom_2',
    'ship_to',
    'Fashion:size',
    'rating',
    'product_type',
    'material',
    'warranty',
    'Fashion:pattern',
    'large_image',
    'stock_status',
    'store_price',
    'valid_from',
    'product_id',
    'isbn',
    'brand_name',
    'savings_percent',
    'stock_quantity',
    'mpn',
    'Fashion:material',
    'terms_of_contract',
    'specifications',
    'merchant_product_second_category',
    'web_offer',
    'data_feed_id',
    'colour',
    'color_normalized_0',
    'color_normalized_1',
    'color_normalized_2',
    'in_stock',
    'parent_product_id',
    'alternate_image_four',
    'promotional_text',
    'brand_id',
    'alternate_image_three',
    'custom_7',
    'european_article_number',
    'dimensions',
    'Fashion:swatch',
    'pre_order',
    'merchant_thumb_url',
    'keywords',
    'delivery_time',
    'last_updated',
    'merchant_category_id',
    'basket_link',
    'category_id',
    'condition',
    'aw_image_url',
    'aw_deep_link',
    'custom_5',
    'merchant_deep_link',
    '\ufeffid',
    'custom_1',
    'short_description',
    'merchant_image_url',
    'alternate_image',
    'aw_thumb_url',
    'merchant_product_third_category',
    'merchant_id',
    'seals',
    'alternate_image_two',
    'delivery_restrictions',
    'base_price',
    'gender',
    'custom_4',
    'commission_group',
    'description2',
    'aw_product_id',
    'custom_9',
    'size_stock_amount',
    'average_rating',
    'Fashion:category',
    'product_model',
    'number_available',
    'reviews',
    'delivery_weight',
    'is_for_sale', 'upc',
    'size_stock_status',
    'product_GTIN',
    'ext_size',
    'Versandkosten Sofortüberweisung',
    'Währung',
    'Versandkosten Lastschrift',
    'Hersteller Artikelnummer HAN',
    'ext_pzn',
    'Anbieter Artikelnummer AAN',
    'Preis (Netto)',
    'Versandkosten PayPal',
    'ext_europäische Artikelnummer EAN',
    'ext_Hersteller Artikelnummer HAN',
    'ext_Versandkosten Sofortüberweisung',
    'ext_Produktkategorie ID', 'ext_Währung'
                               'europäische Artikelnummer EAN',
    'Versandkosten Vorkasse',
    'Vorschaubild-URL',
    'Produktbeschreibung lang',
    'Versandkosten Rechnung',
    'Versandkosten Kreditkarte',
    'Versandkosten Nachnahme',
    'ext_ppu',
    'ext_mpnr',
    'Hersteller',
    'Vorschaubild-URL',
    'merchant_image_url',
    '',
    'europäische Artikelnummer EAN'
    'ext_Grundpreiseinheit',
    'ext_Grundpreis',
    'europäische Artikelnummer EAN',
    'ext_Grundpreiseinheit',
    'ext_Währung',
    'additional_image_link.1',
    'additional_image_link.2'

]

column_index_mapping = {column_name: index for index, column_name in enumerate(column_ord)}
