# ^q%O1KN(LA1Oguu4#Mtm@!0H
merchant_to_identifier = {"asos": "merchant_image_url",
                          "Asos.com DE": "merchant_image_url",
                          "Goertz DE": "merchant_image_url",
                          "Avocadostore DE": "merchant_image_url",
                          "ETHLETIC": "aw_image_url",
                          "HALLHUBER DE": "merchant_image_url",
                          "Hessnatur DE": "merchant_image_url",
                          "HUMANIC AT": "aw_image_url",
                          "i'm walking": "merchant_image_url",
                          "Im walking DE": "merchant_image_url",
                          "JW PEI": "merchant_image_url",
                          "JW PEI DE": "merchant_image_url",
                          "LOVECO - Fair & Vegan Fashion and Shoes": "merchant_image_url",
                          "LOVECO - Fair & Vegan Fashion and Shoes DE": "merchant_image_url",
                          "mirapodo DE": "merchant_image_url",
                          "mirapodo": "merchant_image_url",
                          "muso koroni": "merchant_image_url",
                          "OTTO": "merchant_image_url",
                          "OTTO DE": "merchant_image_url",
                          "promod": "merchant_image_url",
                          "promod DE": "merchant_image_url",
                          "recolution": "merchant_image_url",
                          "SORBAS": "merchant_image_url",
                          "Uli Schott - The unknown brand": "merchant_image_url",
                          "United Colors of Benetton": "merchant_image_url",
                          "Benetton DE": "merchant_image_url",
                          "Nordgreen DACH": "merchant_image_url",
                          "VERO MODA": "merchant_image_url",
                          "Vero Moda DE": "merchant_image_url",
                          "": "aw_image_url",
                          "More & More": "aw_image_url",
                          "LOVECO": "merchant_image_url",
                          "Le Shop Vegan": "aw_deep_link",
                          "recolution DE":"merchant_image_url"
                          }
